# 1. What is NumPy?

NumPy stands for Numerical Python. It is a Python library mainly used for working with numerical data and arrays.

It provides the `ndarray` object and many functions for performing mathematical and statistical operations efficiently.

NumPy is especially useful when working with large amounts of numerical data.

### Example

Imagine we have the marks of 5 students:

50, 60, 70, 80, 90

Instead of processing every value separately, NumPy allows us to store and perform calculations on all these values as an array.

### AI/ML Use Case

NumPy is commonly used in data preprocessing, mathematical calculations, scientific computing, and machine learning.


In [1]:
import numpy as np

marks = np.array([50, 60, 70, 80, 90])

print(marks)
print("Mean:", np.mean(marks))

[50 60 70 80 90]
Mean: 70.0


### Explanation

The code creates a NumPy array containing student marks and calculates their mean.

`np.array()` creates the NumPy array, while `np.mean()` calculates the average.

The output will show the array and its mean value of 70.

NumPy is useful in AI/ML because machine learning involves many numerical calculations.

# 2. Why NumPy?

NumPy makes numerical operations easier and generally more efficient than performing the same operations using normal Python lists.

It provides:
- Fast numerical operations
- Multidimensional arrays
- Mathematical functions
- Statistical functions
- Broadcasting
- Efficient memory usage

# 2. Why NumPy?

NumPy makes numerical operations easier and generally more efficient than performing the same operations using normal Python lists.

It provides:
- Fast numerical operations
- Multidimensional arrays
- Mathematical functions
- Statistical functions
- Broadcasting
- Efficient memory usage

In [2]:
import numpy as np

data = np.array([10, 20, 30, 40])

result = data + 10

print(result)

[20 30 40 50]


### Explanation

NumPy adds 10 to every element of the array.

Expected output:

[20 30 40 50]

This demonstrates how NumPy simplifies numerical operations on multiple values.

# 3. NumPy Arrays (`ndarray`)

A NumPy array is a collection of values stored in a structured way.

The main NumPy array object is called `ndarray`, meaning n-dimensional array.

An array can have one or multiple dimensions.

### Example

A list of marks is a one-dimensional array.

A table containing students and their marks can be represented using a two-dimensional array.

### AI/ML Use Case

Images, datasets, numerical features, and matrices used in machine learning can be represented using NumPy arrays.

In [16]:
import numpy as np

one_dimensional = np.array([10, 20, 30])

two_dimensional = np.array([
    [10, 20],
    [30, 40]
])

print(one_dimensional)
print(two_dimensional)

[10 20 30]
[[10 20]
 [30 40]]


### Explanation

The first array has one dimension, while the second has two dimensions.

NumPy arrays are fundamental for numerical data processing in AI/ML.

# 4. Creating Arrays

NumPy provides several ways to create arrays.

We can create arrays from Python lists or use functions such as:

- `np.zeros()`
- `np.ones()`
- `np.arange()`
- `np.linspace()`

### Example

If we need an array containing five zeros, we can use `np.zeros(5)`.

If we need numbers from 1 to 10, we can use `np.arange()`.

### AI/ML Use Case

These functions are useful for creating initial arrays, numerical ranges, matrices, and data used in calculations.

In [3]:
import numpy as np

zeros = np.zeros(5)
ones = np.ones(5)
numbers = np.arange(1, 11)
values = np.linspace(0, 1, 5)

print("Zeros:", zeros)
print("Ones:", ones)
print("Range:", numbers)
print("Evenly spaced:", values)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Range: [ 1  2  3  4  5  6  7  8  9 10]
Evenly spaced: [0.   0.25 0.5  0.75 1.  ]


### Explanation

The code demonstrates four different ways of creating NumPy arrays.

`zeros()` creates zeros, `ones()` creates ones, `arange()` creates a numerical sequence, and `linspace()` creates evenly spaced values.

# 5. Dimensions

The dimension of a NumPy array describes how many levels of structure the array has.

A one-dimensional array contains a single sequence of values.

A two-dimensional array contains rows and columns.

Higher-dimensional arrays can contain additional levels.

### Example

[1, 2, 3] → 1D

[[1, 2], [3, 4]] → 2D

A collection of multiple 2D matrices can form a 3D array.

### AI/ML Use Case

Images can be represented using multidimensional arrays. Numerical datasets can also contain multiple dimensions.

In [4]:
import numpy as np

array_1d = np.array([1, 2, 3])

array_2d = np.array([
    [1, 2],
    [3, 4]
])

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D:", array_1d.ndim)
print("2D:", array_2d.ndim)
print("3D:", array_3d.ndim)

1D: 1
2D: 2
3D: 3


### Explanation

The `ndim` attribute returns the number of dimensions of an array.

The output will be:

1D: 1
2D: 2
3D: 3

# 6. Shape

The shape of an array tells us how many elements exist along each dimension.

For a 2D array, the shape is represented as:

(rows, columns)

### Example

A table containing 3 rows and 2 columns has a shape of:

(3, 2)

### AI/ML Use Case

Checking the shape of data is important before feeding it into machine learning algorithms.

In [5]:
import numpy as np

data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print("Shape:", data.shape)

Shape: (3, 2)


### Explanation

The `shape` attribute tells us that the array contains 3 rows and 2 columns.

Expected output:

(3, 2)

# 7. Size

The `size` attribute tells us the total number of elements present in an array.

### Example

An array with 3 rows and 2 columns contains:

3 × 2 = 6 elements

In [6]:
import numpy as np

data = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])

print("Total elements:", data.size)

Total elements: 6


### Explanation

`size` returns the total number of elements.

The expected output is 6.

# 8. Data Types

A NumPy array has a data type that describes the type of values stored in it.

Examples include integers, floating-point numbers, and Boolean values.

The data type can be checked using the `dtype` attribute.

### Example

An array containing whole numbers can use an integer data type.

An array containing decimal values can use a floating-point data type.

### AI/ML Use Case

Data types affect memory usage and numerical calculations when processing large datasets.

In [7]:
import numpy as np

integers = np.array([10, 20, 30])
decimals = np.array([10.5, 20.5, 30.5])

print("Integer dtype:", integers.dtype)
print("Decimal dtype:", decimals.dtype)

Integer dtype: int64
Decimal dtype: float64


### Explanation

The `dtype` attribute tells us what type of values the arrays contain.

The first array contains integers and the second contains floating-point values.

# 9. Indexing

Indexing is used to access a specific element from an array.

NumPy uses zero-based indexing, meaning the first element has index 0.

### Example

For:

[10, 20, 30, 40]

Index 0 → 10

Index 2 → 30

In [8]:
import numpy as np

data = np.array([10, 20, 30, 40])

print("First element:", data[0])
print("Third element:", data[2])

First element: 10
Third element: 30


### Explanation

The code accesses individual elements using their index.

This is useful when selecting specific observations or features from data.

# 10. Slicing

Slicing allows us to select a portion of an array instead of selecting only one element.

The general syntax is:

array[start:stop]

### Example

For:

[10, 20, 30, 40, 50]

data[1:4] returns:

[20, 30, 40]

In [9]:
import numpy as np

data = np.array([10, 20, 30, 40, 50])

print(data[1:4])

[20 30 40]


### Explanation

The slice starts at index 1 and stops before index 4.

Therefore, elements at indexes 1, 2, and 3 are selected.

# 11. Reshaping

Reshaping changes the structure of an array without changing the total number of elements.

For example, an array containing 6 values can be reshaped from 1 × 6 into 2 × 3.

### Example

[1, 2, 3, 4, 5, 6]

can be reshaped into:

[[1, 2, 3],

 [4, 5, 6]]

In [10]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6])

reshaped = data.reshape(2, 3)

print(reshaped)

[[1 2 3]
 [4 5 6]]


### Explanation

`reshape(2, 3)` converts the one-dimensional array into 2 rows and 3 columns.

The total number of elements remains 6.

# 12. Flatten

Flatten converts a multidimensional array into a one-dimensional array.

It keeps all the elements but removes the row and column structure.

### Example

[[1, 2],

 [3, 4]]

becomes:

[1, 2, 3, 4]

In [11]:
import numpy as np

data = np.array([
    [1, 2],
    [3, 4]
])

flattened = data.flatten()

print(flattened)

[1 2 3 4]


### Explanation

The `flatten()` method converts the 2D array into a 1D array.

Flattening is commonly useful when converting structured numerical data into a single vector.

# 13. Copy vs View

A copy creates a separate array containing its own data.

A view creates another way of accessing the same underlying data.

Therefore, changing a view can also affect the original array, while changing a copy does not affect the original.

### Example

If two variables refer to the same underlying array data, changing one may change the other.

A copy keeps the data independent.

### AI/ML Use Case

Understanding copies and views helps prevent accidental modification of datasets during preprocessing.

In [12]:
import numpy as np

original = np.array([10, 20, 30])

view = original.view()
copy = original.copy()

view[0] = 100
copy[1] = 200

print("Original:", original)
print("View:", view)
print("Copy:", copy)

Original: [100  20  30]
View: [100  20  30]
Copy: [ 10 200  30]


### Explanation

Changing the view also changes the original array because they share the same underlying data.

Changing the copy does not change the original because the copy has separate data.

# 14. Broadcasting

Broadcasting allows NumPy to perform operations between arrays with compatible shapes without manually repeating values.

For example, a single number can be automatically applied to every element of an array.

### Example

If we have:

[10, 20, 30]

and want to add 5 to every value, NumPy automatically applies 5 to each element.

Result:

[15, 25, 35]

### AI/ML Use Case

Broadcasting is useful for operations such as normalization, scaling, and mathematical transformations of datasets.

In [13]:
import numpy as np

data = np.array([10, 20, 30])

result = data + 5

print(result)

[15 25 35]


### Explanation

NumPy broadcasts the value 5 across every element of the array.

Expected output:

[15 25 35]

# 15. Array Operations

NumPy allows mathematical operations to be performed directly on arrays.

Common operations include:

- Addition
- Subtraction
- Multiplication
- Division
- Power

### Example

Two arrays:

[10, 20, 30]

[1, 2, 3]

can be added element by element.

Result:

[11, 22, 33]

In [14]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


### Explanation

NumPy performs each operation element by element.

This makes mathematical operations on numerical datasets simple and efficient.

# 16. Universal Functions (ufuncs)

Universal functions, or ufuncs, are NumPy functions that perform mathematical operations element by element on arrays.

Examples include:

- `np.sqrt()`
- `np.exp()`
- `np.sin()`
- `np.log()`

They allow mathematical operations to be applied efficiently to entire arrays.

### Example

For the array:

[1, 4, 9, 16]

we can calculate the square root of every value at once.

Result:

[1, 2, 3, 4]

### AI/ML Use Case

Ufuncs are useful in mathematical transformations, feature engineering, statistical calculations, and machine learning algorithms.

In [15]:
import numpy as np

data = np.array([1, 4, 9, 16])

square_roots = np.sqrt(data)

print("Original:", data)
print("Square roots:", square_roots)

Original: [ 1  4  9 16]
Square roots: [1. 2. 3. 4.]


### Explanation

`np.sqrt()` is a NumPy universal function that calculates the square root of every element.

Expected output:

Original: [ 1  4  9 16 ]

Square roots: [1. 2. 3. 4.]

Ufuncs make it easy to apply mathematical transformations to complete arrays.